export const homeData = [
  {
    id: 1,
    name: "Furiosa: A Mad Max Saga (2024)",
    rating: 4.7,
    time: "2024 • R • 2h 28m",
    desc: "The origin story of renegade warrior Furiosa before her encounter and teamup with Mad Max.",
    starring: "Chris Hemsworth • Anya • Taylor-Joy",
    genres: "Action, Adventures, Sci-Fi",
    tags: "Action, Adventures, Horror",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "23 May 2024",
  },
  {
    id: 2,
    name: "Bad Boys: Ride or Die (2024)",
    rating: 7.0,
    time: "R • 1h 55m",
    desc: "This Summer, the world's favorite Bad Boys are back with their iconic mix of edge-of-your seat action and outrageous comedy but this time with a twist: Miami's finest are now on the run.",
    starring: "Vanessa Hudgens • Will Smith • Alexander Ludwig",
    genres: "Action, Adventures, Comedy",
    tags: "Adventures,Animation,Family",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "06 June 2024",
  },
  {
    id: 3,
    name: "House of The Dragon 2022-",
    rating: 8.4,
    time: "TV Series • 2022– • TV-MA • 50m",
    desc: "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen. ",
    starring: "Matt Smith • Emma D'Arcy • Olivia Cooke",
    genres: "Action, Adventures, Drama",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "20-FEB-2022",
  },
  {
    id: 4,
    name: "The Boys",
    rating: 8.7,
    time: "TV Series • 2019–  • TV-MA • 1h",
    desc: "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.",
    starring: "Karl Urban • Jack Quaid • Antony Starr",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "12-Aug-2019",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "The Witcher",
    time:"TV Series • 2019–  • TV-MA • 1h",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "Breaking Bad",
    time: "TV Series • 2008–2013 • TV-MA • 45m",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "lacasa de papel",
    time: "TV Series • 2017–2021 • TV-MA • 1h",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "Fast & Furious: Hobbs & Shaw",
    time: "2019 • PG-13 • 2h 17m",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "The Gray Man (2022)",
    time: "2022 • PG-13 • 2h 2m",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.jpg",
    name: "Dark",
    time: "TV Series • 2017–2020 • TV-MA • 1h",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The Lord of the Rings",
    time: "TV Series • 2022- • TV-14 • 1h",
  },
  {
    id: 3,
    cover: "../images/upcome/u10.jpg",
    name: "The Fall Guy",
    time: "2024 • PG-13 • 2h 6m",
  },
  {
    id: 4,
    cover: "../images/upcome/u9.jpg",
    name: "Beverly Hills Cop: Axel F",
    time: "2024 • R • 1h 58m",
  },
  {
    id: 5,
    cover: "../images/upcome/u8.jpg",
    name: "The Umbrella Academy",
    time: "TV Series • 2019-2024 • TV-14 • 1h",
  },
]

export const trending = [
  {
    id: 1,
    name: "Black Panther",
    rating: 7.3,
    time: "2018 • PG-13 • 2h 14m",
    desc: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country's past.",
    starring: "Chadwick Boseman • Michael B. Jordan • Lupita Nyong'o",
    genres: "Action",
    tags: "Action, Adventures, Sci-Fi",
    cover: "../images/img/slide1.jpg",
    date: "20-Jan-2018",
  },
  {
    id: 2,
    name: "The Umbrella Academy",
    rating: 7.9,
    time: "TV Series • 2019–2024  • TV-14 • 1h",
    desc: "A family of former child heroes, now grown apart, must reunite to continue to protect the world. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Aidan Gallagher • Elliot Page • Tom Hopper",
    tags: "Action, Adventures, Comedy",
    cover: "../images/img/slide2.jpg",
    date: "15-Feb-2019",
  },
  {
    id: 3,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2 h : 22m",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and watermanagement and climate change.",
    starring: "Karen Gilc hist, James Earl Jones",
    genres: "Action",
    tags: "Action, Adventures, Horror",
    cover: "../images/img/slide3.png",
    date: "20-Jan-1997",
  },
]
export const recommended = [
  {
    id: 1,
    cover: "../images/rec/rec1.jpg",
    name: "Army of Thieves",
    time: "2021 • TV-MA • 2h 7m",
  },
  {
    id: 2,
    cover: "../images/rec/rec2.jpg",
    name: "Road House",
    time: "2024 • R • 2h 1m",
  },
  {
    id: 3,
    cover: "../images/rec/rec3.jpg",
    name: "Saw X",
    time: "2023 • R • 1h 58m",
  },
  {
    id: 4,
    cover: "../images/rec/rec4.jpg",
    name: "Under Paris",
    time: "2024 • TV-MA • 1h 44m",
  },
  {
    id: 5,
    cover: "../images/rec/rec5.jpg",
    name: "Baywatch",
    time: "2017 • R • 1h 56m",
  },
]
